CREATE TABLE users(
  user_id BIGINT UNSIGNED NOT NULL,
  user_name TEXT NOT NULL,
  pass_word TEXT NOT NULL,
  description TEXT NULL,
  pic_extension TEXT NOT NULL,
  mail_adress TEXT NOT NULL,
  num_following BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME  DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY(user_id)
);

CREATE TABLE posts(
  post_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  message TEXT,
  media_path TEXT NULL,
  comment_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shared_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  favorite_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP  NOT NULL
);


CREATE TABLE comments(
  comment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE follows(
  data_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  following_id BIGINT UNSIGNED NOT NULL,
  flollowed_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
